server:
  port: 5000
  servlet:
    context-path: /api
spring:
  mvc:
    static-path-pattern: /upload/**
  resources:

   # 管理员：admin asd123
   # 商家：shangjia1 123456
   # 用户：user01 123456

   # 注意改这里，还有反斜杠！！！！！！D:\Code\server
   static-locations: file:D:/Code/server/src/main/resources/static
    # 示例：static-locations: file:此处填写地址/CS_76702/server/src/main/resources/static
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DB?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

